version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lireddit
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_admin:
    image: sosedoff/pgweb
    depends_on:
      - db
    ports:
      - "8081:8081"
  redis:
    image: redis
    ports:
      - "6379:6379"
